# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd37a3a5420ef59574beab326bcce6a4fcb9dd1c54e14ef2f4bdc9612669c88e58f8ce5e60550dbd668f31b57509c66bfe7f63788fc64a63f0ce17ecc30ee456

test:
  secret_key_base: a0040c60e0b7303a860e03d85d2af485f2cd732f35433349438987216cb800404c48cd7da767e49002a29174dd9e42eb8fe2bde71e872f3ad96b104fc26ef294

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
